config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about' => 'homes#about'
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :book, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  
  def after_sign_in_path_for(resource)
    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:imail, :name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def show
    @books = Book.find(params[:id])
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book.id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to user_path(@book.user.id)
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :profile_image_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path(@book.id)
  end

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.book

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name,:introduction, :profile_image_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 mx-auto">
      <h2>Editig Book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
      <%= f.label :Title %><br />
      <%= f.text_field :title, autofocaus: true %><br />
      </div>
      <div class="form-group">
      <%= f.label :Opinion %><br />
      <%= f.text_area :body %>
      </div>
      <div class="form-group">
        <%= f.submit "update"%>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5">
  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが出ています<br />
  <%= @book.errors.full_messages.each do |m| %>
   <%= m %>
  <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-3">
       <h2>User info</h2>
       <table class="table">
         <tbody>
           <tr>
              <th>name</th>
              <th><%= @user.name %></th>
           </tr>
           <tr>
             <th>introduction</th>
             <th><%= @user.introduction %></th>
           </tr>
         </tbody>
      </table>

      <div class="row">
        <%= link_to "User Edit", edit_user_path(@user.id) %>
      </div>

      <div class="row">
        <h2>New Book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
         <%= f.label :Title %><br />
         <%= f.text_field :title %>
        </div>
        <div class="form-group">
         <%= f.label :Opinion %><br />
         <%= f.text_field :body %>
        </div>
        <div class="form-group">
         <%= f.submit "Create Book" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 offset-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <th>
               <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              </th>
              <th>
                <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                <% end %>
              </th>
              <th>
                <%= book.body %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-3">
       <h2>User info</h2>
       <table class="table">
         <%= attachment_image_tag @books.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: 'no_image.jpg' %>
         <tbody>
           <tr>
              <th>name</th>
              <th><%= @books.user.name %></th>
           </tr>
           <tr>
             <th>introduction</th>
             <th><%= @books.user.introduction %></th>
           </tr>
         </tbody>
      </table>

      <div class="row">
        <%= link_to "User Edit", edit_user_path(@books.user.id) %>
      </div>

      <div class="row">
        <h2>New Book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
         <%= f.label :Title %><br />
         <%= f.text_field :title %>
        </div>
        <div class="form-group">
         <%= f.label :Opinion %><br />
         <%= f.text_field :body %>
        </div>
        <div class="form-group">
         <%= f.submit "Create Book" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 offset-1">
      <h2>Book detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <th>
                <%= link_to user_path(@books.user.id) do %>
                 <%= attachment_image_tag @books.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                 <br />
                 <%= @books.user.name %>
               <% end %>
              </th>
              <th>
                <%= link_to book_path(@books.id) do %>
                <%= @books.title %>
                <% end %>
              </th>
              <th>
                <%= @books.body %>
              </th>
              <% if @books.user.id == current_user.id %>
               <th><%= link_to "Edit", edit_book_path(@books.id) %></th>
               <th><%= link_to "Destroy", book_path, method: :delete %></th>
              <% end %>
            </tr>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>ようこそabout画面へ</h1>

app/views/homes/top.html.erb
<h1>ようこそBookersへ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReBookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in?  %>
        <ul>
          <li>
           <%= link_to "Home", user_path(current_user.id) %>
          </li>
          <li>
            <%= link_to "Users", users_path %>
          </li>
          <li>
           <%= link_to "Books", books_path %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
         <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", homes_about_path %></li>
          <li><%= link_to "Sign up",  new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        </ul>
      <% end %>
    </header>
    <main>
    <%= yield %>

    </main>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-5 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
      <%= f.label :Name %><br />
      <%= f.text_field :name, autofocaus: true %><br />
      </div>
      <div class="form-group">
      <%= f.label :Image %><br />
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %><br />
        <%= f.text_field :introduction %>
      </div>
      <div class="form-group">
        <%= f.submit "update"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-3">
       <h2>User info</h2>
       <table class="table">
         <tbody>
           <tr>
              <th>name</th>
              <th><%= @user.name %></th>
           </tr>
           <tr>
             <th>introduction</th>
             <th><%= @user.introduction %></th>
           </tr>
         </tbody>
      </table>

      <div class="row">
        <%= link_to "User Edit", edit_user_path(@user.id) %>
      </div>

      <div class="row">
        <h2>New Book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
         <%= f.label :Title %><br />
         <%= f.text_field :title %>
        </div>
        <div class="form-group">
         <%= f.label :Opinion %><br />
         <%= f.text_field :body %>
        </div>
        <div class="form-group">
         <%= f.submit "Create Book" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 offset-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <th>
             <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            </th>
            <th>
              <%= user.name %>
            </th>
            <th>
              <%= link_to "Show", user_path(user.id) %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-3">
       <h2>User info</h2>
       <table class="table">
         <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: 'no_image.jpg' %>
         <tbody>
           <tr>
              <th>name</th>
              <th><%= @user.name %></th>
           </tr>
           <tr>
             <th>introduction</th>
             <th><%= @user.introduction %></th>
           </tr>
         </tbody>
      </table>

      <div class="row">
        <%= link_to "User Edit", edit_user_path(@user.id) %>
      </div>

      <div class="row">
        <h2>New Book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
         <%= f.label :Title %><br />
         <%= f.text_field :title %>
        </div>
        <div class="form-group">
         <%= f.label :Opinion %><br />
         <%= f.text_field :body %>
        </div>
        <div class="form-group">
         <%= f.submit "Create Book" %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8 offset-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <th>
                <%= link_to user_path(book.user.id) do %>
                 <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </th>
              <th>
                <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                <% end %>
              </th>
              <th>
                <%= book.body %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>